name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: إعداد Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: تثبيت الحزم
        run: npm install

      - name: إنشاء ملف config.js برابط MongoDB السري
        run: |
          echo "const mongoose = require('mongoose');" > db/connect.js
          echo "const MONGODB_URI = '${{ secrets.MONGODB_URI }}';" >> db/connect.js
          echo "const connectDB = async () => {" >> db/connect.js
          echo "  try {" >> db/connect.js
          echo "    await mongoose.connect(MONGODB_URI, { serverSelectionTimeoutMS: 5000 });" >> db/connect.js
          echo "    console.log('✅ تم الاتصال بقاعدة البيانات');" >> db/connect.js
          echo "    mongoose.connection.on('disconnected', () => console.warn('⚠️ تم قطع الاتصال مع MongoDB'));" >> db/connect.js
          echo "    mongoose.connection.on('error', err => console.error('❌ خطأ في الاتصال:', err.message));" >> db/connect.js
          echo "  } catch (err) {" >> db/connect.js
          echo "    console.error('❌ فشل الاتصال بقاعدة البيانات:', err.message);" >> db/connect.js
          echo "    process.exit(1);" >> db/connect.js
          echo "  }" >> db/connect.js
          echo "};" >> db/connect.js
          echo "module.exports = connectDB;" >> db/connect.js

      - name: تشغيل التطبيق أو نشره
        run: npm start # أو node index.js حسب مشروعك
