name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      PORT: ${{ secrets.PORT }}
      NODE_ENV: production  # الأفضل تحديدها مباشرة بدلاً من استخدام secret

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # الترقية إلى الإصدار الأحدث

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # إضافة التخزين المؤقت لتسريع العملية

      - name: Install dependencies
        run: npm ci  # الأفضل من npm install للبيئات الإنتاجية

      - name: Verify MongoDB connection
        run: |
          npm install -g mongodb
          node -e "require('mongodb').MongoClient.connect('$MONGO_URL', { useNewUrlParser: true, useUnifiedTopology: true }).then(() => { console.log('MongoDB connection successful'); }).catch(err => { console.error('MongoDB connection failed:', err); process.exit(1); });"

      - name: Build project (if needed)
        run: npm run build --if-present

      - name: Run tests (if available)
        run: npm test --if-present

      - name: Start the application
        run: npm start
