name: Deploy to Railway

on:
  push:
    branches: [main]

env:
  RAILS_ENV: production
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  MONGO_URL: ${{ secrets.MONGO_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1.175.0
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install MongoDB dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Install gems
        run: bundle install

      - name: Build assets
        run: bundle exec rails assets:precompile

      - uses: abatilo/actions-railway@v2.2.0
        with:
          service-id: ${{ secrets.RAILWAY_SERVICE_ID }}
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          command: deploy
