name: Validate Before Deploy (Railway)

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      PORT: ${{ secrets.PORT }}
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install production dependencies
        run: npm install --omit=dev

      - name: Verify MongoDB connection
        run: |
          node -e "
            const { MongoClient } = require('mongodb');
            const client = new MongoClient(process.env.MONGO_URL);
            client.connect()
              .then(() => {
                console.log('✅ تم الاتصال بـ MongoDB بنجاح');
                return client.db().admin().ping();
              })
              .then(() => {
                console.log('✅ تم التحقق من ping بنجاح');
                return client.close();
              })
              .catch(err => {
                console.error('❌ فشل الاتصال بـ MongoDB:', err);
                process.exit(1);
              });
          "

      - name: Run migrations (if needed)
        run: npm run migrate --if-present
